### ISSUE TITLE
[🧪] - Expand the E2E test cases

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#71]
This is in umbrella ticket. You can found subtask under this ticket (or create new one if you can not found), please work on the subtask instead.

## Describe the request

Background story:

This repo is owned by SDET (Soft. Dev Eng in Test) person, it should demonstrate the strong side of the owner. This repo have a minimum E2E setup using playwright which can be our entry to the next level to be a good portfolio and example of automated and well-tested application.

## Subtasks

- [ ] Run E2E task in separate two device: desktop and mobile
- [ ] Leverage the [Annotations](https://playwright.dev/docs/test-annotations) to group the test cases
- [ ] Introduce the visual test
- [ ] New test case: Sort functionality
- [ ] New test case: Hide column functionality
- [ ] New test case: Action buttons assertion
- [ ] New test case: Detail page
